server:
  port: 8080
  session:
    cookie:
      name: OAUTH2SESSION
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/oauth
    username: root
    driver-class-name: org.mariadb.jdbc.Driver
    password: admin123456!@#
  jpa:
    show-sql: false
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      use-new-id-generator-mappings: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka