server:
  port: 8001
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/uap
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: admin123456!@#
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
  redis:
    host: 127.0.0.1
  cache: 
    #type: redis
    type: jcache
    jcache:
      config: classpath:jcache.xml
    cache-names:
    - user
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka